[package]
name = "flo-w3gs"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
flo-util = { path = "../util" }

bitflags = "1"
thiserror = "1"
lazy_static = "1"
prost = "0.9"
futures = "0.3.24"
tokio = { version = "1.21.2", features = ["net", "io-util"] }
tokio-stream = { version = "0.1.10", features = ["net"] }
tokio-util = { version = "0.6", features = ["codec", "net"] }
rand = "0.8"
crc32fast = "1.3"

[build-dependencies]
prost-build = "0.9"
